platform:ios,'8.0'
use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!

def pods

pod 'SDWebImage'
pod 'FLAnimatedImage', '~> 1.0'
pod 'SlideMenuControllerSwift'
pod 'Alamofire', '~> 4.5.1'
pod 'YYWebImage'

end

target 'KJ-HitComic' do
    pods
end



